apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  namespace: django-forum
data:
  mysql.cnf: |-
    [client]
    default-character-set = utf8mb4
    
    [mysql]
    default-character-set = utf8mb4
     
    [mysqld]
    default-time-zone='+8:00'
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    datadir = /var/lib/mysql
    log_error = /var/log/mysql/error.log
    sql_mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: django-forum
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-user: YWRtaW4=
  mysql-password: enpyYWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-forum-mysql
  namespace: django-forum
  labels:
    app: django-forum-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-forum-mysql
      appCluster: django-forum-mysql-cluster
  template:
    metadata:
      labels:
        app: django-forum-mysql
        appCluster: django-forum-mysql-cluster
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - django-forum-mysql
              topologyKey: kubernetes.io/hostname
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - django-forum-redis
            topologyKey: kubernetes.io/hostname
      containers:
        - name: django-forum-mysql
          image: mysql:5.7
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: MYSQL_DATABASE
              value: forum
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 180
            periodSeconds: 60
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-conf
              mountPath: /etc/mysql/conf.d
      volumes:
      - name: "mysql-conf"
        configMap:
          name: "mysql-conf"
          items:
            - key: "mysql.cnf"
              path: "mysql.cnf"
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: django-forum-mysql
---
kind: Service
apiVersion: v1
metadata:
  name: django-forum-mysql
  namespace: django-forum
  labels:
    app: django-forum-mysql
spec:
  type: ClusterIP
  ports:
    - name: django-forum-mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: django-forum-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-forum-mysql
  namespace: django-forum
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"
  storageClassName: nfs-client